spring:
  application:
    name: order-service

  # Global Spring Retry configuration (can be overridden per method)
  retry:
    max-attempts: 3 # Default number of retries
    backoff:
      delay: 500 # Initial delay in ms
      multiplier: 2.0 # multiplier for next retry delay (500, 1000, 2000...)

#redis configuration
  redis:
    host: localhost
    port: 6379

#Vault Configuration - With Spring Boot 2.4+ and Spring Cloud Vault 3+, using bootstrap.yaml is deprecated in favor of keeping all configuration in application.yaml (or .properties) and using the new Config Data API. You can migrate by moving your Vault config to application.yaml and adding:
#  cloud:
#    vault:
#      uri: http://127.0.0.1:8200                          # Vault server URL
#      #token: hvs.UeRA9uUXVXflT5OGoT9Emxih                 # Use root token only for dev - Added this token in ENV Var for this app
#      #SPRING_CLOUD_VAULT_TOKEN=hvs.UeRA9uUXVXflT5OGoT9Emxih
#      kv:
#        enabled: true
#        backend: secret
#        default-context: ORDER-SVC
#
#  config:
#    import: vault://              # Automatically import secrets from Vault path

  security:                               #Spring Security - Order also acts as Clients - need Client Config.
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-9957757.okta.com/oauth2/default

      client: #Order Service also acts as Clients - need Client Config.
        registration:
          my-internal-client: # any name
            provider: okta
            authorization-grant-type: client_credentials            # Client Config
            scope: internal                                            #use for internal service communication
            client-id: 0oatqzpi5co360ajB697                                                         #${OKTA_CLIENT_ID}
            client-secret: ruyfeRq5i6gJBah2J5TM0Yr0s-3XIAmzC_w2oaxRAsPdU7HuQq3Ru0n6rVi2lry3         #${OKTA_CLIENT_SECRET}

        provider:
          okta:
            issuer-uri: https://integrator-9957757.okta.com/oauth2/default

  #PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    driver-class-name: org.postgresql.Driver
    username: postgres          #${spring.datasource.username}
    password: admin             #${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect       #org.hibernate.dialect.H2Dialect <-H2 Dialect

  #KAFKA Configuration
  kafka:
    bootstrap-servers: localhost:9092  #my-kafka.kafka.svc.cluster.local:9092    #kubernetes config url
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'

order:
  topic: order-events

server:
  port: 8000

#Okta Configuration
okta:
  oauth2:
    issuer: https://integrator-9957757.okta.com/oauth2/default
    audience: api://default

#Circuit-Breaker Configuration - Resilience4j  - MOVE THIS TO API GATEWAY LEVEL
resilience4j:
  circuitBreaker:
    instances:
      paymentService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED # Or TIME_BASED
        sliding-window-size: 10 # Number of calls to calculate error rate
        minimum-number-of-calls: 5 # Min calls before circuit can open
        failure-rate-threshold: 50 # % of calls that must fail to open the circuit
        wait-duration-in-open-state: 30s # How long to stay OPEN before switching to HALF-OPEN
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true #or automated recovery unless business demands operator intervention

#Add Eureka Server Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

#H2 DB Connection Details
  #datasource:
    #url: jdbc:h2:mem:ordersdb
    #driver-class-name: org.h2.Driver
    #username: sa
   # password:
  #h2:
    #console:
      #enabled: true
      #path: /h2-console

logging:
  level:
    org.springframework.data.redis.serializer: DEBUG
    com.fasterxml.jackson.databind: DEBUG


